// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_ceBjGJxBhyi9nsiI4Rgu8SM5jjmPIt8',
    appId: '1:688118988830:web:43cdcd3a130e42e65e6e0f',
    messagingSenderId: '688118988830',
    projectId: 'babyshop-1bebd',
    authDomain: 'babyshop-1bebd.firebaseapp.com',
    databaseURL: 'https://babyshop-1bebd-default-rtdb.firebaseio.com/',
    storageBucket: 'babyshop-1bebd.firebasestorage.app',
    measurementId: 'G-8XJMFF0ZGD',

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSnEonP1_INL_EIkg54ShlM9S2ScKXoS0',
    appId: '1:688118988830:android:c51b5ce2aab389735e6e0f',
    messagingSenderId: '688118988830',
    projectId: 'babyshop-1bebd',
    databaseURL: 'https://babyshop-1bebd-default-rtdb.firebaseio.com/',
    storageBucket: 'babyshop-1bebd.firebasestorage.app',


  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKmt_2QY-5TgAK_XIowKEe55OD4ir_EpU',
    appId: '1:688118988830:ios:a668d81a0939a5695e6e0f',
    messagingSenderId: '688118988830',
    projectId: 'babyshop-1bebd',
    databaseURL: 'https://babyshop-1bebd-default-rtdb.firebaseio.com/',
    storageBucket: 'babyshop-1bebd.firebasestorage.app',
    iosClientId: '688118988830-8eqskmn23c8mpfsl9doac31rfrjncdlk.apps.googleusercontent.com',
    iosBundleId: 'com.example.babyShopHub',


  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKmt_2QY-5TgAK_XIowKEe55OD4ir_EpU',
    appId: '1:688118988830:ios:a668d81a0939a5695e6e0f',
    messagingSenderId: '688118988830',
    projectId: 'babyshop-1bebd',
    databaseURL: 'https://babyshop-1bebd-default-rtdb.firebaseio.com/',
    storageBucket: 'babyshop-1bebd.firebasestorage.app',
    iosClientId: '688118988830-8eqskmn23c8mpfsl9doac31rfrjncdlk.apps.googleusercontent.com',
    iosBundleId: 'com.example.babyShopHub',


  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_ceBjGJxBhyi9nsiI4Rgu8SM5jjmPIt8',
    appId: '1:688118988830:web:dfc36e605a2e111a5e6e0f',
    messagingSenderId: '688118988830',
    projectId: 'babyshop-1bebd',
    authDomain: 'babyshop-1bebd.firebaseapp.com',
    databaseURL: 'https://babyshop-1bebd-default-rtdb.firebaseio.com/',
    storageBucket: 'babyshop-1bebd.firebasestorage.app',
    measurementId: 'G-BG3RQLECXT',


  );
}
